### ISSUE TITLE
Bug: Files should be static

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [Andy-Python-Programmer/p5-studio#10]
If we currently see `p5-studio-creator` it generates the template correctly but in the template the files are not actually static. They are pulled from a cdn. So we need to make them static 👍

**Comment by ghost** [comment]
I would love to work on this

**Comment by Andy-Python-Programmer** [comment]
Ok thanks for picking this issue up to solve. 

### Information
Todo:
1. Create a folder called libraries
2. Read the p5 and p5 sound lib from `.txt` file 
3. cd libraries
4. Write the files and you are done 👍

**Comment by Andy-Python-Programmer** [comment]
Getting errors needs to be fixed.

`UnhandledPromiseRejectionWarning`
